[theme]
base = "light"
primaryColor = "#1FB2DE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EAF9FD"
textColor = "#0F385A"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
